### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by rus64** [alvinj/LearnFunctionalProgrammingBook#2]
Really enjoying the book so far. 

I'm currently working through the ToDoList example and have noticed a couple of things that appear to be missing:
- This repo doesn't seem to include the ToDoList example (it is mentioned that the user could navigate to the ToDoList directory and run the app on page 91)
- The `CollectionUtils.removeElementByIndex(rows, indexToDelete)` helper function is used a few times, and there is a note on page 107 letting us know that we can find the implementation in the appendix, but searching for it I don't seem to be able to find it.

Cheers

**Comment by alvinj** [comment]
Oops, I’m sorry about that, and thank you for letting me know. I’ll add that code as soon as possible.

Until then, one thing I can do quickly is show the `removeElementByIndex` function here:

```scala
object CollectionUtils:

    def removeElementByIndex[A](seq: Seq[A], index: Int): Seq[A] =
        if index < 0 || index >= seq.length then
            seq
        else if index == 0 then
            seq.tail
        else
            val (a, b) = seq.splitAt(index)
            a ++ b.tail
```

**Comment by alvinj** [comment]
I’m very sorry about the long delay on this, but hopefully I have uploaded the correct example now. (I had several different examples of this application, and needed a little time to make sure I grabbed the one that matches the book.)

**Comment by rus64** [comment]
Amazing, thanks!
